name: Security

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci || npm install
      - name: Generate SBOM (Syft)
        uses: anchore/sbom-action@v0
        with:
          path: .
          output-file: sbom.spdx.json
      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          format: 'table'
          exit-code: '0'
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v2.3.6
        with:
          args: "detect --redact --no-git -v"
